// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_INCLUDED_test_2eproto
#define PROTOBUF_INCLUDED_test_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_test_2eproto 

namespace protobuf_test_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_test_2eproto
namespace my {
class DevNode;
class DevNodeDefaultTypeInternal;
extern DevNodeDefaultTypeInternal _DevNode_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Node;
class NodeDefaultTypeInternal;
extern NodeDefaultTypeInternal _Node_default_instance_;
}  // namespace my
namespace google {
namespace protobuf {
template<> ::my::DevNode* Arena::CreateMaybeMessage<::my::DevNode>(Arena*);
template<> ::my::Message* Arena::CreateMaybeMessage<::my::Message>(Arena*);
template<> ::my::Node* Arena::CreateMaybeMessage<::my::Node>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace my {

// ===================================================================

class Node : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:my.Node) */ {
 public:
  Node();
  virtual ~Node();

  Node(const Node& from);

  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Node(Node&& from) noexcept
    : Node() {
    *this = ::std::move(from);
  }

  inline Node& operator=(Node&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Node& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Node* internal_default_instance() {
    return reinterpret_cast<const Node*>(
               &_Node_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Node* other);
  friend void swap(Node& a, Node& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Node* New() const final {
    return CreateMaybeMessage<Node>(NULL);
  }

  Node* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Node>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Node& from);
  void MergeFrom(const Node& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Node* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string operation = 1;
  bool has_operation() const;
  void clear_operation();
  static const int kOperationFieldNumber = 1;
  const ::std::string& operation() const;
  void set_operation(const ::std::string& value);
  #if LANG_CXX11
  void set_operation(::std::string&& value);
  #endif
  void set_operation(const char* value);
  void set_operation(const char* value, size_t size);
  ::std::string* mutable_operation();
  ::std::string* release_operation();
  void set_allocated_operation(::std::string* operation);

  // required .my.Message m_message = 2;
  bool has_m_message() const;
  void clear_m_message();
  static const int kMMessageFieldNumber = 2;
  private:
  const ::my::Message& _internal_m_message() const;
  public:
  const ::my::Message& m_message() const;
  ::my::Message* release_m_message();
  ::my::Message* mutable_m_message();
  void set_allocated_m_message(::my::Message* m_message);

  // @@protoc_insertion_point(class_scope:my.Node)
 private:
  void set_has_operation();
  void clear_has_operation();
  void set_has_m_message();
  void clear_has_m_message();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr operation_;
  ::my::Message* m_message_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:my.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Message* other);
  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(NULL);
  }

  Message* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .my.DevNode dev = 4;
  int dev_size() const;
  void clear_dev();
  static const int kDevFieldNumber = 4;
  ::my::DevNode* mutable_dev(int index);
  ::google::protobuf::RepeatedPtrField< ::my::DevNode >*
      mutable_dev();
  const ::my::DevNode& dev(int index) const;
  ::my::DevNode* add_dev();
  const ::google::protobuf::RepeatedPtrField< ::my::DevNode >&
      dev() const;

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional string password = 2;
  bool has_password() const;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // optional string error = 3;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 3;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // @@protoc_insertion_point(class_scope:my.Message)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_password();
  void clear_has_password();
  void set_has_error();
  void clear_has_error();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::my::DevNode > dev_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DevNode : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:my.DevNode) */ {
 public:
  DevNode();
  virtual ~DevNode();

  DevNode(const DevNode& from);

  inline DevNode& operator=(const DevNode& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DevNode(DevNode&& from) noexcept
    : DevNode() {
    *this = ::std::move(from);
  }

  inline DevNode& operator=(DevNode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DevNode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DevNode* internal_default_instance() {
    return reinterpret_cast<const DevNode*>(
               &_DevNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(DevNode* other);
  friend void swap(DevNode& a, DevNode& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DevNode* New() const final {
    return CreateMaybeMessage<DevNode>(NULL);
  }

  DevNode* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DevNode>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DevNode& from);
  void MergeFrom(const DevNode& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DevNode* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string status = 2;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  const ::std::string& status() const;
  void set_status(const ::std::string& value);
  #if LANG_CXX11
  void set_status(::std::string&& value);
  #endif
  void set_status(const char* value);
  void set_status(const char* value, size_t size);
  ::std::string* mutable_status();
  ::std::string* release_status();
  void set_allocated_status(::std::string* status);

  // optional string ISDN = 3;
  bool has_isdn() const;
  void clear_isdn();
  static const int kISDNFieldNumber = 3;
  const ::std::string& isdn() const;
  void set_isdn(const ::std::string& value);
  #if LANG_CXX11
  void set_isdn(::std::string&& value);
  #endif
  void set_isdn(const char* value);
  void set_isdn(const char* value, size_t size);
  ::std::string* mutable_isdn();
  ::std::string* release_isdn();
  void set_allocated_isdn(::std::string* isdn);

  // @@protoc_insertion_point(class_scope:my.DevNode)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_status();
  void clear_has_status();
  void set_has_isdn();
  void clear_has_isdn();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr status_;
  ::google::protobuf::internal::ArenaStringPtr isdn_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Node

// required string operation = 1;
inline bool Node::has_operation() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Node::set_has_operation() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Node::clear_has_operation() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Node::clear_operation() {
  operation_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_operation();
}
inline const ::std::string& Node::operation() const {
  // @@protoc_insertion_point(field_get:my.Node.operation)
  return operation_.GetNoArena();
}
inline void Node::set_operation(const ::std::string& value) {
  set_has_operation();
  operation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:my.Node.operation)
}
#if LANG_CXX11
inline void Node::set_operation(::std::string&& value) {
  set_has_operation();
  operation_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:my.Node.operation)
}
#endif
inline void Node::set_operation(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_operation();
  operation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:my.Node.operation)
}
inline void Node::set_operation(const char* value, size_t size) {
  set_has_operation();
  operation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:my.Node.operation)
}
inline ::std::string* Node::mutable_operation() {
  set_has_operation();
  // @@protoc_insertion_point(field_mutable:my.Node.operation)
  return operation_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Node::release_operation() {
  // @@protoc_insertion_point(field_release:my.Node.operation)
  if (!has_operation()) {
    return NULL;
  }
  clear_has_operation();
  return operation_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Node::set_allocated_operation(::std::string* operation) {
  if (operation != NULL) {
    set_has_operation();
  } else {
    clear_has_operation();
  }
  operation_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), operation);
  // @@protoc_insertion_point(field_set_allocated:my.Node.operation)
}

// required .my.Message m_message = 2;
inline bool Node::has_m_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Node::set_has_m_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Node::clear_has_m_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Node::clear_m_message() {
  if (m_message_ != NULL) m_message_->Clear();
  clear_has_m_message();
}
inline const ::my::Message& Node::_internal_m_message() const {
  return *m_message_;
}
inline const ::my::Message& Node::m_message() const {
  const ::my::Message* p = m_message_;
  // @@protoc_insertion_point(field_get:my.Node.m_message)
  return p != NULL ? *p : *reinterpret_cast<const ::my::Message*>(
      &::my::_Message_default_instance_);
}
inline ::my::Message* Node::release_m_message() {
  // @@protoc_insertion_point(field_release:my.Node.m_message)
  clear_has_m_message();
  ::my::Message* temp = m_message_;
  m_message_ = NULL;
  return temp;
}
inline ::my::Message* Node::mutable_m_message() {
  set_has_m_message();
  if (m_message_ == NULL) {
    auto* p = CreateMaybeMessage<::my::Message>(GetArenaNoVirtual());
    m_message_ = p;
  }
  // @@protoc_insertion_point(field_mutable:my.Node.m_message)
  return m_message_;
}
inline void Node::set_allocated_m_message(::my::Message* m_message) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete m_message_;
  }
  if (m_message) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      m_message = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, m_message, submessage_arena);
    }
    set_has_m_message();
  } else {
    clear_has_m_message();
  }
  m_message_ = m_message;
  // @@protoc_insertion_point(field_set_allocated:my.Node.m_message)
}

// -------------------------------------------------------------------

// Message

// optional string id = 1;
inline bool Message::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& Message::id() const {
  // @@protoc_insertion_point(field_get:my.Message.id)
  return id_.GetNoArena();
}
inline void Message::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:my.Message.id)
}
#if LANG_CXX11
inline void Message::set_id(::std::string&& value) {
  set_has_id();
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:my.Message.id)
}
#endif
inline void Message::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:my.Message.id)
}
inline void Message::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:my.Message.id)
}
inline ::std::string* Message::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:my.Message.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_id() {
  // @@protoc_insertion_point(field_release:my.Message.id)
  if (!has_id()) {
    return NULL;
  }
  clear_has_id();
  return id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:my.Message.id)
}

// optional string password = 2;
inline bool Message::has_password() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_password() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_password() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_password();
}
inline const ::std::string& Message::password() const {
  // @@protoc_insertion_point(field_get:my.Message.password)
  return password_.GetNoArena();
}
inline void Message::set_password(const ::std::string& value) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:my.Message.password)
}
#if LANG_CXX11
inline void Message::set_password(::std::string&& value) {
  set_has_password();
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:my.Message.password)
}
#endif
inline void Message::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:my.Message.password)
}
inline void Message::set_password(const char* value, size_t size) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:my.Message.password)
}
inline ::std::string* Message::mutable_password() {
  set_has_password();
  // @@protoc_insertion_point(field_mutable:my.Message.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_password() {
  // @@protoc_insertion_point(field_release:my.Message.password)
  if (!has_password()) {
    return NULL;
  }
  clear_has_password();
  return password_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    set_has_password();
  } else {
    clear_has_password();
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:my.Message.password)
}

// optional string error = 3;
inline bool Message::has_error() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_error() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_error() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_error();
}
inline const ::std::string& Message::error() const {
  // @@protoc_insertion_point(field_get:my.Message.error)
  return error_.GetNoArena();
}
inline void Message::set_error(const ::std::string& value) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:my.Message.error)
}
#if LANG_CXX11
inline void Message::set_error(::std::string&& value) {
  set_has_error();
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:my.Message.error)
}
#endif
inline void Message::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:my.Message.error)
}
inline void Message::set_error(const char* value, size_t size) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:my.Message.error)
}
inline ::std::string* Message::mutable_error() {
  set_has_error();
  // @@protoc_insertion_point(field_mutable:my.Message.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_error() {
  // @@protoc_insertion_point(field_release:my.Message.error)
  if (!has_error()) {
    return NULL;
  }
  clear_has_error();
  return error_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    set_has_error();
  } else {
    clear_has_error();
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:my.Message.error)
}

// repeated .my.DevNode dev = 4;
inline int Message::dev_size() const {
  return dev_.size();
}
inline void Message::clear_dev() {
  dev_.Clear();
}
inline ::my::DevNode* Message::mutable_dev(int index) {
  // @@protoc_insertion_point(field_mutable:my.Message.dev)
  return dev_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::my::DevNode >*
Message::mutable_dev() {
  // @@protoc_insertion_point(field_mutable_list:my.Message.dev)
  return &dev_;
}
inline const ::my::DevNode& Message::dev(int index) const {
  // @@protoc_insertion_point(field_get:my.Message.dev)
  return dev_.Get(index);
}
inline ::my::DevNode* Message::add_dev() {
  // @@protoc_insertion_point(field_add:my.Message.dev)
  return dev_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::my::DevNode >&
Message::dev() const {
  // @@protoc_insertion_point(field_list:my.Message.dev)
  return dev_;
}

// -------------------------------------------------------------------

// DevNode

// required string name = 1;
inline bool DevNode::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DevNode::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DevNode::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DevNode::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& DevNode::name() const {
  // @@protoc_insertion_point(field_get:my.DevNode.name)
  return name_.GetNoArena();
}
inline void DevNode::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:my.DevNode.name)
}
#if LANG_CXX11
inline void DevNode::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:my.DevNode.name)
}
#endif
inline void DevNode::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:my.DevNode.name)
}
inline void DevNode::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:my.DevNode.name)
}
inline ::std::string* DevNode::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:my.DevNode.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DevNode::release_name() {
  // @@protoc_insertion_point(field_release:my.DevNode.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DevNode::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:my.DevNode.name)
}

// optional string status = 2;
inline bool DevNode::has_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DevNode::set_has_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DevNode::clear_has_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DevNode::clear_status() {
  status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_status();
}
inline const ::std::string& DevNode::status() const {
  // @@protoc_insertion_point(field_get:my.DevNode.status)
  return status_.GetNoArena();
}
inline void DevNode::set_status(const ::std::string& value) {
  set_has_status();
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:my.DevNode.status)
}
#if LANG_CXX11
inline void DevNode::set_status(::std::string&& value) {
  set_has_status();
  status_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:my.DevNode.status)
}
#endif
inline void DevNode::set_status(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_status();
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:my.DevNode.status)
}
inline void DevNode::set_status(const char* value, size_t size) {
  set_has_status();
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:my.DevNode.status)
}
inline ::std::string* DevNode::mutable_status() {
  set_has_status();
  // @@protoc_insertion_point(field_mutable:my.DevNode.status)
  return status_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DevNode::release_status() {
  // @@protoc_insertion_point(field_release:my.DevNode.status)
  if (!has_status()) {
    return NULL;
  }
  clear_has_status();
  return status_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DevNode::set_allocated_status(::std::string* status) {
  if (status != NULL) {
    set_has_status();
  } else {
    clear_has_status();
  }
  status_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), status);
  // @@protoc_insertion_point(field_set_allocated:my.DevNode.status)
}

// optional string ISDN = 3;
inline bool DevNode::has_isdn() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DevNode::set_has_isdn() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DevNode::clear_has_isdn() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DevNode::clear_isdn() {
  isdn_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_isdn();
}
inline const ::std::string& DevNode::isdn() const {
  // @@protoc_insertion_point(field_get:my.DevNode.ISDN)
  return isdn_.GetNoArena();
}
inline void DevNode::set_isdn(const ::std::string& value) {
  set_has_isdn();
  isdn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:my.DevNode.ISDN)
}
#if LANG_CXX11
inline void DevNode::set_isdn(::std::string&& value) {
  set_has_isdn();
  isdn_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:my.DevNode.ISDN)
}
#endif
inline void DevNode::set_isdn(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_isdn();
  isdn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:my.DevNode.ISDN)
}
inline void DevNode::set_isdn(const char* value, size_t size) {
  set_has_isdn();
  isdn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:my.DevNode.ISDN)
}
inline ::std::string* DevNode::mutable_isdn() {
  set_has_isdn();
  // @@protoc_insertion_point(field_mutable:my.DevNode.ISDN)
  return isdn_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DevNode::release_isdn() {
  // @@protoc_insertion_point(field_release:my.DevNode.ISDN)
  if (!has_isdn()) {
    return NULL;
  }
  clear_has_isdn();
  return isdn_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DevNode::set_allocated_isdn(::std::string* isdn) {
  if (isdn != NULL) {
    set_has_isdn();
  } else {
    clear_has_isdn();
  }
  isdn_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), isdn);
  // @@protoc_insertion_point(field_set_allocated:my.DevNode.ISDN)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace my

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_test_2eproto
